python tools/device_node_assignment.py \
  --device-id "$INPUT_DEVICE_ID" \
  --lat "$INPUT_LATITUDE" \
  --lon "$INPUT_LONGITUDE" \
  --elev "$INPUT_ELEVATION" \
  --elev-unit "$INPUT_ELEVATION_UNIT" \
  --service-code "$INPUT_SERVICE_CODE" \
  --owner-mark "$INPUT_OWNER_MARK"

#!/usr/bin/env python3
import argparse
import json
import math
import os
from dataclasses import dataclass, asdict
from datetime import datetime, timezone
from typing import Dict, Any

import qrcode


@dataclass
class GeoPoint:
    latitude: float
        longitude: float
            elevation_m: float


            @dataclass
            class NodeCell:
                lat_index: int
                    lon_index: int
                        elev_index: int

                            @property
                                def id(self) -> str:
                                        return f"cell_lat{self.lat_index}_lon{self.lon_index}_elev{self.elev_index}"

                                            def to_dict(self) -> Dict[str, Any]:
                                                    d = asdict(self)
                                                            d["id"] = self.id
                                                                    return d


                                                                    def convert_elevation_to_meters(value: float, unit: str) -> float:
                                                                        unit = unit.lower()
                                                                            if unit == "m":
                                                                                    return value
                                                                                        if unit == "ft":
                                                                                                return value * 0.3048
                                                                                                    raise ValueError(f"Unsupported elevation unit: {unit}")


                                                                                                    def quantize(value: float, unit_size: float) -> int:
                                                                                                        return math.floor(value / unit_size)


                                                                                                        def build_node_cell(point: GeoPoint,
                                                                                                                            lat_unit_size_deg: float = 0.01,
                                                                                                                                                lon_unit_size_deg: float = 0.01,
                                                                                                                                                                    elev_unit_size_m: float = 10.0) -> NodeCell:
                                                                                                                                                                        lat_index = quantize(point.latitude, lat_unit_size_deg)
                                                                                                                                                                            lon_index = quantize(point.longitude, lon_unit_size_deg)
                                                                                                                                                                                elev_index = quantize(point.elevation_m, elev_unit_size_m)
                                                                                                                                                                                    return NodeCell(lat_index=lat_index, lon_index=lon_index, elev_index=elev_index)


                                                                                                                                                                                    def now_iso() -> str:
                                                                                                                                                                                        return datetime.now(timezone.utc).isoformat()


                                                                                                                                                                                        def build_device_identity_bundle(
                                                                                                                                                                                            device_id: str,
                                                                                                                                                                                                point: GeoPoint,
                                                                                                                                                                                                    node_cell: NodeCell,
                                                                                                                                                                                                        service_code: str,
                                                                                                                                                                                                            owner_mark: str,
                                                                                                                                                                                                            ) -> Dict[str, Any]:
                                                                                                                                                                                                                primary_uri = f"https://blackcorp.me/fellowstar/devices/{device_id}"
                                                                                                                                                                                                                    side_uri = f"https://side.blackcorp.me/rebelstar/{node_cell.id}"

                                                                                                                                                                                                                        return {
                                                                                                                                                                                                                                "device_id": device_id,
                                                                                                                                                                                                                                        "owner_mark": owner_mark,
                                                                                                                                                                                                                                                "service_code": service_code,
                                                                                                                                                                                                                                                        "geo_point": asdict(point),
                                                                                                                                                                                                                                                                "node_cell": node_cell.to_dict(),
                                                                                                                                                                                                                                                                        "uris": {
                                                                                                                                                                                                                                                                                    "primary": primary_uri,
                                                                                                                                                                                                                                                                                                "side": side_uri,
                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                "inspection": {
                                                                                                                                                                                                                                                                                                                            "status": "registered",
                                                                                                                                                                                                                                                                                                                                        "last_checked_at": now_iso(),
                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                        "witness": {
                                                                                                                                                                                                                                                                                                                                                                    "record_log_agent": "mesh-witness-v1",
                                                                                                                                                                                                                                                                                                                                                                                "intent_interpretation": "device_registration",
                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                            }


                                                                                                                                                                                                                                                                                                                                                                                            def build_qr_payload(bundle: Dict[str, Any]) -> str:
                                                                                                                                                                                                                                                                                                                                                                                                core = {
                                                                                                                                                                                                                                                                                                                                                                                                        "device_id": bundle["device_id"],
                                                                                                                                                                                                                                                                                                                                                                                                                "node_cell_id": bundle["node_cell"]["id"],
                                                                                                                                                                                                                                                                                                                                                                                                                        "service_code": bundle["service_code"],
                                                                                                                                                                                                                                                                                                                                                                                                                                "primary_uri": bundle["uris"]["primary"],
                                                                                                                                                                                                                                                                                                                                                                                                                                        "side_uri": bundle["uris"]["side"],
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                return json.dumps(core, separators=(",", ":"))


                                                                                                                                                                                                                                                                                                                                                                                                                                                def generate_qr_image(payload: str, device_id: str, out_dir: str = "artifacts/qr") -> str:
                                                                                                                                                                                                                                                                                                                                                                                                                                                    os.makedirs(out_dir, exist_ok=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        filename = os.path.join(out_dir, f"{device_id}_qr.png")
                                                                                                                                                                                                                                                                                                                                                                                                                                                            img = qrcode.make(payload)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                img.save(filename)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return filename


                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def parse_args() -> argparse.Namespace:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        parser = argparse.ArgumentParser(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                description="Assign adaptive node, QR, and URIs to a registered device."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        parser.add_argument("--device-id", required=True, type=str)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            parser.add_argument("--lat", "--latitude", dest="latitude", required=True, type=float)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                parser.add_argument("--lon", "--longitude", dest="longitude", required=True, type=float)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    parser.add_argument("--elev", "--elevation", dest="elevation", required=True, type=float)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        parser.add_argument("--elev-unit", dest="elev_unit", default="m",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                choices=["m", "ft", "M", "FT"])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    parser.add_argument("--service-code", required=True, type=str)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        parser.add_argument("--owner-mark", required=False, type=str,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                default="FELLOWSTAR | REBEL STAR")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return parser.parse_args()


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def main() -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        args = parse_args()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elev_m = convert_elevation_to_meters(args.elevation, args.elev_unit)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                point = GeoPoint(latitude=args.latitude,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     longitude=args.longitude,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          elevation_m=elev_m)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              node_cell = build_node_cell(point)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  bundle = build_device_identity_bundle(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          device_id=args.device_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  point=point,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          node_cell=node_cell,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  service_code=args.service_code,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          owner_mark=args.owner_mark,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  qr_payload = build_qr_payload(bundle)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      qr_path = generate_qr_image(qr_payload, args.device_id)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          bundle["qr"] = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "payload": qr_payload,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "image_path": qr_path,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  os.makedirs("artifacts", exist_ok=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      json_path = os.path.join("artifacts", f"{args.device_id}_identity.json")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          with open(json_path, "w", encoding="utf-8") as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  json.dump(bundle, f, indent=2)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      print("=== Device Adaptive Node & QR Assignment ===")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          print(json.dumps(bundle, indent=2))


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              main()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
